name: pytest-test

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: write

jobs:
  pytest-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Check Repo...
      uses: actions/checkout@v5

    - name: Set up Python...
      uses: actions/setup-python@v5
      with:
        python-version: "3.14"

    - name: Setup pytest...
      run: |
        pip install --upgrade pip
        pip install pytest
        mkdir tests/samples_out
    - name: Run tests...
      run: |
        pytest
